# Generated by Django 3.2.6 on 2021-08-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GreenSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('establishmentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenAreaManagement.establishmenttype')),
            ],
        ),
    ]
