# Generated by Django 3.2.6 on 2021-08-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenAreaManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishmenttype',
            old_name='libel',
            new_name='name',
        ),
    ]
