# Generated by Django 3.2.6 on 2021-09-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenAreaManagement', '0003_rename_name_establishmenttype_libel'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenspace',
            name='positionLgt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenspace',
            name='positionLtd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
