# Generated by Django 3.2.6 on 2021-08-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.EmailField(default='myname@default.com', max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('subscriptionDate', models.DateTimeField()),
                ('validityDate', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberManagement.member')),
            ],
        ),
    ]
