# Generated by Django 3.2.6 on 2021-08-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='barcodeImg',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='member',
            name='qr_codeImg',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
