# Generated by Django 3.2.6 on 2021-08-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberManagement', '0003_auto_20210819_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='barcode',
            new_name='barcodeImg',
        ),
    ]
