# Generated by Django 3.2.6 on 2021-08-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberManagement', '0004_rename_barcode_member_barcodeimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.FloatField(),
        ),
    ]
