# Generated by Django 3.2.6 on 2021-08-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberManagement', '0005_alter_subscription_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriptionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='validityDate',
            field=models.DateField(),
        ),
    ]
