# Generated by Django 3.2.6 on 2021-09-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberManagement', '0006_auto_20210827_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='code',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
