# Generated by Django 3.2.6 on 2021-09-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberManagement', '0007_alter_member_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='code',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
